// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * @fileoverview Defines structures and lists related to Google Advanced Services
 * as used within Apps Script projects and their manifests. This includes the
 * interface for an advanced service and a comprehensive list of publicly
 * available advanced services.
 */

// Reference for Apps Script manifest structure:
// https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/appsscript.json

/**
 * Represents a Google Advanced Service that can be enabled in an Apps Script project.
 */
export interface AdvancedService {
  /** The symbol used to access the service in Apps Script (e.g., `Drive`, `Gmail`). */
  readonly userSymbol: string;
  /** The identifier of the service (e.g., `drive`, `gmail`). */
  readonly serviceId: string;
  /** The version of the service to be used (e.g., `v3`, `v1`). */
  readonly version: string;
}

/**
 * A comprehensive list of all publicly available Google Advanced Services
 * that can be enabled in an Apps Script project.
 *
 * This list was generated by:
 * 1. Creating a new project on script.google.com.
 * 2. Navigating to "Resources" > "Advanced Google Services".
 * 3. Enabling all listed services.
 * 4. Viewing the manifest file ("View" > "Show manifest file" or `appsscript.json`).
 * 5. Extracting the `dependencies.enabledAdvancedServices` array from the manifest.
 */
export const PUBLIC_ADVANCED_SERVICES: AdvancedService[] = [
  {
    userSymbol: 'AdminDirectory',
    version: 'directory_v1',
    serviceId: 'admin',
  },
  {
    userSymbol: 'AdminGroupsMigration',
    version: 'v1',
    serviceId: 'groupsmigration',
  },
  {
    userSymbol: 'AdminGroupsSettings',
    version: 'v1',
    serviceId: 'groupssettings',
  },
  {
    userSymbol: 'AdminLicenseManager',
    version: 'v1',
    serviceId: 'licensing',
  },
  {
    userSymbol: 'AdminReports',
    version: 'reports_v1',
    serviceId: 'admin',
  },
  {
    userSymbol: 'AdminReseller',
    version: 'v1',
    serviceId: 'reseller',
  },
  {
    userSymbol: 'AdSense',
    version: 'v2',
    serviceId: 'adsense',
  },
  {
    userSymbol: 'Analytics',
    version: 'v3',
    serviceId: 'analytics',
  },
  {
    userSymbol: 'AnalyticsAdmin',
    version: 'v1beta',
    serviceId: 'analyticsadmin',
  },
  {
    userSymbol: 'AnalyticsData',
    version: 'v1beta',
    serviceId: 'analyticsdata',
  },
  {
    userSymbol: 'AnalyticsReporting',
    version: 'v4',
    serviceId: 'analyticsreporting',
  },
  {
    userSymbol: 'Area120Tables',
    version: 'v1alpha1',
    serviceId: 'area120tables',
  },
  {
    userSymbol: 'BigQuery',
    version: 'v2',
    serviceId: 'bigquery',
  },
  {
    userSymbol: 'Calendar',
    version: 'v3',
    serviceId: 'calendar',
  },
  {
    userSymbol: 'Chat',
    version: 'v1',
    serviceId: 'chat',
  },
  {
    userSymbol: 'Classroom',
    version: 'v1',
    serviceId: 'classroom',
  },
  {
    userSymbol: 'Docs',
    version: 'v1',
    serviceId: 'docs',
  },
  {
    userSymbol: 'DoubleClickCampaigns',
    version: 'v4',
    serviceId: 'dfareporting',
  },
  {
    userSymbol: 'Drive',
    version: 'v3',
    serviceId: 'drive',
  },
  {
    userSymbol: 'DriveActivity',
    version: 'v2',
    serviceId: 'driveactivity',
  },
  {
    userSymbol: 'DriveLabels',
    version: 'v2beta',
    serviceId: 'drivelabels',
  },
  {
    userSymbol: 'Gmail',
    version: 'v1',
    serviceId: 'gmail',
  },
  {
    userSymbol: 'People',
    version: 'v1',
    serviceId: 'peopleapi',
  },
  {
    userSymbol: 'Sheets',
    version: 'v4',
    serviceId: 'sheets',
  },
  {
    userSymbol: 'ShoppingContent',
    version: 'v2.1',
    serviceId: 'content',
  },
  {
    userSymbol: 'Slides',
    version: 'v1',
    serviceId: 'slides',
  },
  {
    userSymbol: 'TagManager',
    version: 'v2',
    serviceId: 'tagmanager',
  },
  {
    userSymbol: 'Tasks',
    version: 'v1',
    serviceId: 'tasks',
  },
  {
    userSymbol: 'WorkspaceEvents',
    version: 'v1',
    serviceId: 'workspaceevents',
  },
  {
    userSymbol: 'YouTube',
    version: 'v3',
    serviceId: 'youtube',
  },
  {
    userSymbol: 'YouTubeAnalytics',
    version: 'v1',
    serviceId: 'youtubeAnalytics',
  },
  {
    userSymbol: 'YouTubeContentId',
    version: 'v1',
    serviceId: 'youtubePartner',
  },
];
