/**
 * Google API Types
 */

// Also see:
// https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/appsscript.json
export interface AdvancedService {
  readonly userSymbol: string;
  readonly serviceId: string;
  readonly version: string;
}

/**
 * This is a list of all public Advanced Services.
 *
 * It was generated by:
 * 1. script.google.com/create
 * 1. Resources > Advanced Google Services
 * 1. Enable all services
 * 1. View > Show manifest file
 * 1. View appsscript.json
 */
export const PUBLIC_ADVANCED_SERVICES: AdvancedService[] = [
  {
    userSymbol: 'AdminDirectory',
    version: 'directory_v1',
    serviceId: 'admin',
  },
  {
    userSymbol: 'AdminGroupsMigration',
    version: 'v1',
    serviceId: 'groupsmigration',
  },
  {
    userSymbol: 'AdminGroupsSettings',
    version: 'v1',
    serviceId: 'groupssettings',
  },
  {
    userSymbol: 'AdminLicenseManager',
    version: 'v1',
    serviceId: 'licensing',
  },
  {
    userSymbol: 'AdminReports',
    version: 'reports_v1',
    serviceId: 'admin',
  },
  {
    userSymbol: 'AdminReseller',
    version: 'v1',
    serviceId: 'reseller',
  },
  {
    userSymbol: 'AdSense',
    version: 'v2',
    serviceId: 'adsense',
  },
  {
    userSymbol: 'Analytics',
    version: 'v3',
    serviceId: 'analytics',
  },
  {
    userSymbol: 'AnalyticsAdmin',
    version: 'v1beta',
    serviceId: 'analyticsadmin',
  },
  {
    userSymbol: 'AnalyticsData',
    version: 'v1beta',
    serviceId: 'analyticsdata',
  },
  {
    userSymbol: 'AnalyticsReporting',
    version: 'v4',
    serviceId: 'analyticsreporting',
  },
  {
    userSymbol: 'Area120Tables',
    version: 'v1alpha1',
    serviceId: 'area120tables',
  },
  {
    userSymbol: 'BigQuery',
    version: 'v2',
    serviceId: 'bigquery',
  },
  {
    userSymbol: 'Calendar',
    version: 'v3',
    serviceId: 'calendar',
  },
  {
    userSymbol: 'Chat',
    version: 'v1',
    serviceId: 'chat',
  },
  {
    userSymbol: 'Classroom',
    version: 'v1',
    serviceId: 'classroom',
  },
  {
    userSymbol: 'Docs',
    version: 'v1',
    serviceId: 'docs',
  },
  {
    userSymbol: 'DoubleClickCampaigns',
    version: 'v4',
    serviceId: 'dfareporting',
  },
  {
    userSymbol: 'Drive',
    version: 'v3',
    serviceId: 'drive',
  },
  {
    userSymbol: 'DriveActivity',
    version: 'v2',
    serviceId: 'driveactivity',
  },
  {
    userSymbol: 'DriveLabels',
    version: 'v2beta',
    serviceId: 'drivelabels',
  },
  {
    userSymbol: 'Gmail',
    version: 'v1',
    serviceId: 'gmail',
  },
  {
    userSymbol: 'People',
    version: 'v1',
    serviceId: 'peopleapi',
  },
  {
    userSymbol: 'Sheets',
    version: 'v4',
    serviceId: 'sheets',
  },
  {
    userSymbol: 'ShoppingContent',
    version: 'v2.1',
    serviceId: 'content',
  },
  {
    userSymbol: 'Slides',
    version: 'v1',
    serviceId: 'slides',
  },
  {
    userSymbol: 'TagManager',
    version: 'v2',
    serviceId: 'tagmanager',
  },
  {
    userSymbol: 'Tasks',
    version: 'v1',
    serviceId: 'tasks',
  },
  {
    userSymbol: 'WorkspaceEvents',
    version: 'v1',
    serviceId: 'workspaceevents',
  },
  {
    userSymbol: 'YouTube',
    version: 'v3',
    serviceId: 'youtube',
  },
  {
    userSymbol: 'YouTubeAnalytics',
    version: 'v1',
    serviceId: 'youtubeAnalytics',
  },
  {
    userSymbol: 'YouTubeContentId',
    version: 'v1',
    serviceId: 'youtubePartner',
  },
];
